version: "3.7"

services:
  backend:
    build: ./backend
    container_name: backend
    tty: true
    networks:
      - node-network
    ports:
      - "3333:3333"

  frontend:
    build: ./frontend
    container_name: frontend
    tty: true
    networks:
      - node-network
    ports:
      - "3000:3000"
    depends_on: 
      - backend
     
networks:
  node-network:
    driver: bridge
